name: graphql-workshop

services:
  bus-tickets-app-postgres:
    container_name: bus-tickets-app-postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: bus_tickets_app
      POSTGRES_PASSWORD: strong_secret_password
      POSTGRES_DB: bus-tickets-app
    networks: [bus-tickets-app]
    ports: ["5432:5432"]
    volumes:
      - type: volume
        source: bus-tickets-app-postgres-data
        target: /var/lib/postgresql/data

networks:
  bus-tickets-app:
    name: bus-tickets-app

volumes:
  bus-tickets-app-postgres-data: